#!/bin/bash

if [ -z $HAKUNA_API ];
	then echo "HAKUNA_API environment variable is not set" ; exit 1
fi

if [ -z $HAKUNA_HOST ];
	then echo "HAKUNA_HOST environment variable is not set" ; exit 1
fi

StatusTimer() {

	TIMER_STATUS=$(curl --silent -X "GET" "https://${HAKUNA_HOST}/api/v1/timer" \
		-H "Accept-Version: v1" \
		-H "X-Auth-Token: ${HAKUNA_API}")

	TIMER_STATUS_DURATION=$(echo $TIMER_STATUS | jq --raw-output .duration)

	echo -e "Running Timer:\t\t$TIMER_STATUS_DURATION"

}

StatusDay() {
	DATE_TODAY=$(date +%Y-%m-%d)


	TIMER_GET_ALL_TIME_ENTRIES=$(curl --silent -X "GET" "https://${HAKUNA_HOST}/api/v1/time_entries?start_date=${DATE_TODAY}&end_date=${DATE_TODAY}" \
		-H "Accept-Version: v1" \
		-H "X-Auth-Token: ${HAKUNA_API}")

	TIMER_GET_ALL_TIME_ENTRIES_SECONDS=$(echo $TIMER_GET_ALL_TIME_ENTRIES | jq '.[].duration_in_seconds' | awk 'BEGIN { sum=0 } { sum+=$1 } END {print sum }')
	CONVERT_TO_HOURS=$(printf '%dh:%dm:%ds\n' $(($TIMER_GET_ALL_TIME_ENTRIES_SECONDS/3600)) $(($TIMER_GET_ALL_TIME_ENTRIES_SECONDS%3600/60)) $(($TIMER_GET_ALL_TIME_ENTRIES_SECONDS%60)))

	echo -e "Summary Today:\t\t$CONVERT_TO_HOURS"
}

StatusWeek() {

	DATE_MONDAY=$(date -dlast-monday +%Y-%m-%d)
	DATE_SUNDAY=$(date -dnext-sunday +%Y-%m-%d)

	TIMER_GET_ALL_TIME_ENTRIES=$(curl --silent -X "GET" "https://${HAKUNA_HOST}/api/v1/time_entries?start_date=${DATE_MONDAY}&end_date=${DATE_SUNDAY}" \
		-H "Accept-Version: v1" \
		-H "X-Auth-Token: ${HAKUNA_API}")

	TIMER_GET_ALL_TIME_ENTRIES_SECONDS=$(echo $TIMER_GET_ALL_TIME_ENTRIES | jq '.[].duration_in_seconds' | awk 'BEGIN { sum=0 } { sum+=$1 } END {print sum }')
	CONVERT_TO_HOURS=$(printf '%dh:%dm:%ds\n' $(($TIMER_GET_ALL_TIME_ENTRIES_SECONDS/3600)) $(($TIMER_GET_ALL_TIME_ENTRIES_SECONDS%3600/60)) $(($TIMER_GET_ALL_TIME_ENTRIES_SECONDS%60)))

	echo -e "Summary Week:\t\t$CONVERT_TO_HOURS"

}

StartTimer() {

	TIMER_STATUS=$(curl --silent -X "POST" "https://${HAKUNA_HOST}/api/v1/timer" \
		-H "Accept-Version: v1" \
		-H "X-Auth-Token: ${HAKUNA_API}" \
		-H "Content-Type: application/json; charset=utf-8" \
		-d '{
			"task_id": "1"
		}')

	TIMER_STATUS_START_TIME=$(echo $TIMER_STATUS | jq --raw-output .start_time)

	echo -e "Start Time: $TIMER_STATUS_START_TIME"

}

StopTimer() {

	TIMER_STATUS=$(curl --silent -X "PUT" "https://${HAKUNA_HOST}/api/v1/timer" \
		-H "X-Auth-Token: ${HAKUNA_API}")

	TIMER_STATUS_START_TIME=$(echo $TIMER_STATUS | jq --raw-output .start_time)
	TIMER_STATUS_END_TIME=$(echo $TIMER_STATUS | jq --raw-output .end_time)
	TIMER_STATUS_DURATION=$(echo $TIMER_STATUS | jq --raw-output .duration)

	echo -e "Start Time: $TIMER_STATUS_START_TIME\nEnd Time: $TIMER_STATUS_END_TIME\nDuration: $TIMER_STATUS_DURATION"

}

case $1 in
	"")
		StatusTimer
		StatusDay
		StatusWeek
		;;
	status)
		StatusTimer
		StatusDay
		StatusWeek
		;;
	start)
		StartTimer
		;;
	stop)
		StopTimer
		;;
esac
