#!/bin/bash

if [ -z $HAKUNA_API ];
	then echo "HAKUNA_API environment variable is not set" ; exit 1
fi

if [ -z $HAKUNA_HOST ];
	then echo "HAKUNA_HOST environment variable is not set" ; exit 1
fi

Status() {

	TIMER_STATUS=$(curl --silent -X "GET" "https://${HAKUNA_HOST}/api/v1/timer" \
		-H "Accept-Version: v1" \
		-H "X-Auth-Token: ${HAKUNA_API}")

	TIMER_STATUS_DURATION=$(echo $TIMER_STATUS | jq --raw-output .duration)

	echo -e "Duration: $TIMER_STATUS_DURATION"

}

StartTimer() {

	curl --silent -X "POST" "https://${HAKUNA_HOST}/api/v1/timer" \
		-H "Accept-Version: v1" \
		-H "X-Auth-Token: ${HAKUNA_API}" \
		-H "Content-Type: application/json; charset=utf-8" \
		-d '{
			"task_id": "1"
		}' | jq

}

StopTimer() {

	TIMER_STATUS=$(curl --silent -X "PUT" "https://${HAKUNA_HOST}/api/v1/timer" \
		-H "X-Auth-Token: ${HAKUNA_API}")

	TIMER_STATUS_START_TIME=$(echo $TIMER_STATUS | jq --raw-output .start_time)
	TIMER_STATUS_END_TIME=$(echo $TIMER_STATUS | jq --raw-output .end_time)
	TIMER_STATUS_DURATION=$(echo $TIMER_STATUS | jq --raw-output .duration)

	echo -e "Start Time: $TIMER_STATUS_START_TIME\nEnd Time: $TIMER_STATUS_END_TIME\nDuration: $TIMER_STATUS_DURATION"

}

case $1 in
	"")
		Status
		;;
	status)
		Status
		;;
	start)
		StartTimer
		;;
	stop)
		StopTimer
		;;
esac
